version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm run jest

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check prettier
          command: npm run prettier
          when: always

  deploy:
    docker:
      - image: circleci/node:8

    steps:
      - run:
          name: Deploy to production
          command: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
