version: 2
jobs:
  build:

    macos:
      xcode: 9.4.1

    environment:
      # https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8

    steps:
      - add_ssh_keys

      - checkout

      - run:
          name: Clone submodules
          command: git submodule update --init --recursive

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: sudo bundle install

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          # https://circleci.com/docs/2.0/ios-migrating-from-1-2/#installing-cocoapods
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install

      - run:
          name: Disable code signing
          command: ./scripts/disable_code_signing.sh

      - run:
          name: Build app server
          command: ./scripts/app_server_build.sh

      - run:
          name: Build for running unit tests
          command: ./scripts/unit_tests_build.sh

      - run:
          environment:
            INTEGRATION_TESTS: "false"
          name: Run unit tests
          command: ./scripts/unit_tests_run.sh

      - run:
          name: Run code formatter and linter
          command: bundle exec fastlane lint

      # - run:
      #     name: Build and run tests
      #     command: fastlane scan
      #     environment:
      #       SCAN_DEVICE: iPhone 6
      #       SCAN_SCHEME: WebTests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml

      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results

      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
